// <auto-generated />
using System;
using DataInsights.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataInsights.API.Migrations.PostgreSQLDbMigrations
{
    [DbContext(typeof(PostgreSQLDb))]
    [Migration("20250922094015_pgMigrations")]
    partial class pgMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataInsights.API.Models.Customer", b =>
                {
                    b.Property<int>("_customerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_customerID"));

                    b.Property<string>("_customerEmail")
                        .HasColumnType("text");

                    b.Property<string>("_customerName")
                        .HasColumnType("text");

                    b.HasKey("_customerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DataInsights.API.Models.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Product_ID"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Product_Description")
                        .HasColumnType("text");

                    b.Property<string>("Product_Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Product_ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataInsights.API.Models.Sale", b =>
                {
                    b.Property<int>("Sales_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sales_ID"));

                    b.Property<int>("Customer_ID")
                        .HasColumnType("integer");

                    b.Property<int?>("Customer_customerID")
                        .HasColumnType("integer");

                    b.Property<int?>("Product_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total_Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Sales_ID");

                    b.HasIndex("Customer_customerID");

                    b.HasIndex("Product_ID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("DataInsights.API.Models.Sale", b =>
                {
                    b.HasOne("DataInsights.API.Models.Customer", "Customer")
                        .WithMany("_sales")
                        .HasForeignKey("Customer_customerID");

                    b.HasOne("DataInsights.API.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("Product_ID");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataInsights.API.Models.Customer", b =>
                {
                    b.Navigation("_sales");
                });

            modelBuilder.Entity("DataInsights.API.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
